### ISSUE TITLE
parameters of internal strm link references

### ISSUE THREAD

**Issue by alex83100** [stereodruid/plugin.video.osmosis#35] opened 2017-09-16 07:30 UTC
hello, despite the configuration "original plugin" in the parameters of internal strm link references, I have the osmosis plugin in the link strm. the problem was not present in older versions

**Comment by Maven85** [comment] 2018-01-08 14:39
Thanks for your report.

The problem is resolved in the future-branch now.

**Closed as completed by Maven85** 2018-01-08 14:39 UTC
